server:
  port: 8080

spring:
  application:
    name: springboot_board
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_board?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: "JyOh"
    password: "0107"
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
